### Análise dos dados argentinos ###

In [1]:
import pandas as pd

In [2]:
df_ncm = pd.read_csv('databases/govbr/NCM.csv', delimiter=';', encoding='cp1252')

In [56]:
ArgentinaEXP_IMP = pd.read_csv('databases/secem_mercosur/NCM_2026-08-15.csv')

In [57]:
ArgentinaEXP_IMP[["Exportaciones", "Importaciones (FOB)", "Importaciones (CIF)"]] = ArgentinaEXP_IMP[["Exportaciones", "Importaciones (FOB)", "Importaciones (CIF)"]].astype(int)

In [58]:
ArgentinaEXP_IMP.rename(columns={'NCM':'CO_NCM'}, inplace=True)

In [59]:
ArgentinaEXP_IMP = ArgentinaEXP_IMP.merge(df_ncm[['CO_NCM', 'NO_NCM_POR']], on = 'CO_NCM', how='left')

In [60]:
ArgentinaEXP_IMP['NO_NCM_POR'] = ArgentinaEXP_IMP[
    'NO_NCM_POR'
].fillna(ArgentinaEXP_IMP['Descripción'])

In [61]:
ArgentinaEXP_IMP = ArgentinaEXP_IMP[['CO_NCM', 'NO_NCM_POR', 'Exportaciones']]

In [62]:
ArgentinaEXP_IMP = ArgentinaEXP_IMP.sort_values('Exportaciones', ascending=False)

In [63]:
ArgentinaEXP_IMP['Exportaciones'].sum()

np.int64(87076964335)

### Análise de Exportações da Argentina por País

In [64]:
ArgentinaExportacaoPorPais = pd.read_csv('databases/secem_mercosur/NCM_2026-08-16 PAIS.csv')

In [65]:
ArgentinaExportacaoPorPais[["Exportaciones", "Importaciones (CIF)"]] = ArgentinaExportacaoPorPais[["Exportaciones", "Importaciones (CIF)"]].astype(int)

In [66]:
ArgentinaExportacaoPorPais = ArgentinaExportacaoPorPais[['País', 'Exportaciones', 'Importaciones (CIF)']]

In [67]:
ArgentinaExportacaoPorPais.sort_values('Exportaciones', ascending= False).head(20)

               País  Exportaciones  Importaciones (CIF)
20           Brasil    12760949017          18356844514
33            China     9706246998          17940826377
186  Estados Unidos     8172064963           6610069655
32            Chile     6280741120            870213438
76            India     5471506041           1436189874
160         Vietnam     2730483493           1322172842
137            Perú     2547845227            344671711
122    Países Bajos     2073690668            464750554
170           Suiza     2062879951            699272998
188         Uruguay     1764537669            590070394
153  Arabia Saudita     1576153369             94931765
136        Paraguay     1369082261           2957978711
193   Indeterminado     1363010117           1207040620
29           Canadá     1300504915            418997711
77        Indonesia     1230900536            492340085
165          España     1222299228           1167266746
105         Malasia     1181659375            277611289
2           Argelia     1169774441            118604490
62         Alemania     1108539032           3135678215
82           Italia     1090225499           1564036875

In [68]:
ArgentinaExportacaoPorPais['Exportaciones'].sum()

np.int64(87076964992)

In [69]:
ArgentinaExportacaoPorPais['País'].nunique()

205

### Análise Importações por país

In [70]:
ArgentinaImportNCM = pd.read_csv('databases/secem_mercosur/imports_by_country.csv', delimiter=';', encoding='utf-8')

In [71]:
ArgentinaImportNCM['CIF(USD)'] = pd.to_numeric(
    ArgentinaImportNCM['CIF(USD)'].str.replace(',', '.', regex=False), errors='coerce'
).astype(int)

In [72]:
ArgentinaImportNCM.rename(columns={'NCM':'CO_NCM'}, inplace=True)

In [73]:
ArgentinaImportNCM = ArgentinaImportNCM.merge(df_ncm[['CO_NCM', 'NO_NCM_POR']], on = 'CO_NCM', how='left')

In [74]:
ArgentinaImportNCM = ArgentinaImportNCM[['CO_NCM', 'NO_NCM_POR', 'Pais', 'CIF(USD)']]

In [75]:
ArgentinaImportNCMAgregado = ArgentinaImportNCM.groupby(['CO_NCM', 'NO_NCM_POR','Pais'])['CIF(USD)'].sum().reset_index()

In [76]:
ArgentinaImportNCMAgregado['CIF(USD)'].sum()

np.int64(74584478161)

In [77]:
ArgentinaImportNCMAgregado.sort_values('CIF(USD)', ascending=False, inplace=True)

In [78]:
ArgentinaImportNCMAgregado.head(15)

,CO_NCM,NO_NCM_POR,Pais,CIF(USD)
1196,12019000,"Soja, mesmo triturada, exceto para semeadura",Paraguay,2063579846
66082,87032210,"Automóveis com motor explosão, de cilindrada s...",Brasil,1318765686
66071,87032100,"Automóveis com motor explosão, de cilindrada n...",Brasil,1222595645
66103,87032310,"Automóveis com motor explosão, 1500 < cm3 <= 3...",Brasil,913565572
65989,87012100,"Tratores rodoviários para semirreboques, unica...",Brasil,895326987
3902,27101921,Gasóleo (óleo diesel),Estados Unidos,587130712
66239,87043190,Outros veículos automóveis com motor a explosã...,Brasil,548569930
60359,85177900,"Outras partes de aparelhos telefônicos, inclui...",Viet Nam,443065366
60318,85177900,"Outras partes de aparelhos telefônicos, inclui...",China,442718234
4058,27111100,Gás natural liquefeito,Estados Unidos,350510806
66818,87084080,Outras caixas de marchas,Japón,339010289
52285,84713019,Outras máquinas digitais para processamento de...,China,311284901
11534,30021590,"Outros produtos imunológicos, apresentados em ...",Suiza,299639647
66144,87034000,"Outros veículos, equipados para propulsão, sim...",Brasil,286490528
66201,87042210,"Chassis com motor diesel e cabina, 5 toneladas...",Brasil,284504556

In [79]:
ArgentinaImportNCM.groupby(['CO_NCM', 'NO_NCM_POR'])['CIF(USD)'].sum().reset_index().sort_values('CIF(USD)', ascending=False).head(15)

        CO_NCM                                         NO_NCM_POR    CIF(USD)
354   12019000       Soja, mesmo triturada, exceto para semeadura  2241009749
7192  87032210  Automóveis com motor explosão, de cilindrada s...  1717730353
7194  87032310  Automóveis com motor explosão, 1500 < cm3 <= 3...  1711427997
7191  87032100  Automóveis com motor explosão, de cilindrada n...  1249018457
2262  30021590  Outros produtos imunológicos, apresentados em ...   962418673
7176  87012100  Tratores rodoviários para semirreboques, unica...   927991555
6815  85177900  Outras partes de aparelhos telefônicos, inclui...   894190206
7220  87043190  Outros veículos automóveis com motor a explosã...   844396143
833   27101921                              Gasóleo (óleo diesel)   840570049
7258  87084080                           Outras caixas de marchas   767614217
2462  31054000  Diidrogeno-ortofosfato de amônio (fosfato mono...   695993237
2439  31021010  Ureia, mesmo em solução aquosa, com teor de ni...   695655345
7252  87082999  Outras partes e acessórios de carrocerias para...   692113336
845   27111100                             Gás natural liquefeito   608085374
7284  87089990  Outras partes e acessórios para tratores e veí...   605435032

In [80]:
ArgentinaImportNCM.groupby('Pais')['CIF(USD)'].sum().reset_index().sort_values('CIF(USD)', ascending=False).head(15)

                              Pais     CIF(USD)
22                          Brasil  18356830382
34                           China  17940803137
58                  Estados Unidos   6610056529
152  República Federal de Alemania   3135667032
142                       Paraguay   2957977871
174                      Tailandia   2116801890
127                         México   1722769244
93                          Italia   1564027749
85                           India   1436182872
95                           Japón   1424775451
195                       Viet Nam   1322169872
84      Indeterminado (continente)   1206024914
57                          España   1167242181
66                         Francia   1123944866
33                           Chile    870211327

### Nova análise de Exportações Argentinas

In [81]:
ArgentinaExportNCM = pd.read_csv('databases/secem_mercosur/exports_by_country.csv', delimiter=';', encoding='utf-8')

In [82]:
ArgentinaExportNCM.info()

<class 'pandas.DataFrame'>
RangeIndex: 11681 entries, 0 to 11680
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Ano       11681 non-null  int64
 1   NCM       11681 non-null  str
 2   Pdes      11681 non-null  int64
 3   Pnet(kg)  11676 non-null  str
 4   FOB(USD)  11681 non-null  str
 5   Pais      11681 non-null  str
dtypes: int64(2), str(4)
memory usage: 547.7 KB

In [83]:
ArgentinaExportNCM['FOB(USD)'] = pd.to_numeric(
    ArgentinaExportNCM['FOB(USD)'].str.replace(',', '.', regex=False), errors='coerce'
).astype(int)

In [84]:
ArgentinaExportNCM.rename(columns={'NCM':'CO_NCM'}, inplace=True)

In [85]:
df_ncm['CO_NCM'] = df_ncm['CO_NCM'].astype('str')

In [86]:
ArgentinaExportNCM = ArgentinaExportNCM.merge(df_ncm[['CO_NCM', 'NO_NCM_POR']], on = 'CO_NCM', how='left')

In [87]:
ArgentinaExportNCM = ArgentinaExportNCM[['CO_NCM', 'NO_NCM_POR', 'Pais', 'FOB(USD)']]

In [88]:
ArgentinaExportNCMAgregado = ArgentinaExportNCM.groupby(['CO_NCM', 'NO_NCM_POR','Pais'])['FOB(USD)'].sum().reset_index()

In [89]:
ArgentinaExportNCMAgregado['FOB(USD)'].sum()

np.int64(71329807194)

In [90]:
ArgentinaExportNCMAgregado.sort_values('FOB(USD)', ascending=False, inplace=True)

In [91]:
ArgentinaExportNCMAgregado.head(15)

,CO_NCM,NO_NCM_POR,Pais,FOB(USD)
204,12019000,"Soja, mesmo triturada, exceto para semeadura",China,4585522701
432,15071000,"Óleo de soja, em bruto, mesmo degomado",India,3712134302
1626,27090010,Óleos brutos de petróleo,Estados Unidos,3488185311
8238,87042190,"Outros veículos automóveis com motor diesel, p...",Brasil,3087833458
5119,71081210,"Bulhão dourado (bullion doré), em formas bruta...",Suiza,2018003412
1624,27090010,Óleos brutos de petróleo,Chile,1927385770
907,2023000,"Carnes desossadas de bovino, congeladas",China,1512000995
1480,23040010,"Farinhas e pellets, da extração do óleo de soja",Viet Nam,1218675111
4,10019900,"Outros trigos e misturas de trigo com centeio,...",Brasil,1210796529
118,10059010,"Milho em grão, exceto para semeadura",Viet Nam,1104599775
99,10059010,"Milho em grão, exceto para semeadura",Perú,942794296
484,15121110,"Óleo de girassol, em bruto",India,787156280
1715,28369100,Carbonatos de litio,China,673274671
88,10059010,"Milho em grão, exceto para semeadura",Malasia,672258244
5118,71081210,"Bulhão dourado (bullion doré), em formas bruta...",India,654658337

In [92]:
ArgentinaExportNCMAgregado = ArgentinaExportNCMAgregado.groupby(['CO_NCM', 'NO_NCM_POR'])['FOB(USD)'].sum().reset_index().sort_values('FOB(USD)', ascending=False)

In [93]:
ArgentinaExportNCMAgregado.head(40)

        CO_NCM                                         NO_NCM_POR    FOB(USD)
221   23040010    Farinhas e pellets, da extração do óleo de soja  8205400643
6     10059010               Milho em grão, exceto para semeadura  6478131400
260   27090010                           Óleos brutos de petróleo  6457246244
58    15071000             Óleo de soja, em bruto, mesmo degomado  6271461148
31    12019000       Soja, mesmo triturada, exceto para semeadura  4795877151
1839  87042190  Outros veículos automóveis com motor diesel, p...  4240325735
1     10019900  Outros trigos e misturas de trigo com centeio,...  3073437481
1186  71081210  Bulhão dourado (bullion doré), em formas bruta...  3071366765
147    2023000            Carnes desossadas de bovino, congeladas  2181398088
67    15121110                         Óleo de girassol, em bruto  1372708913
143    2013000  Carnes desossadas de bovino, frescas ou refrig...  1284028542
32    12024200            Amendoins descascados, mesmo triturados   955676557
298   28369100                                Carbonatos de litio   756350845
275   27112100                       Gás natural no estado gasoso   659232097
1834  87032100  Automóveis com motor explosão, de cilindrada n...   608083588
200   22042100  Outros vinhos, mostos de uvas, fermentados, im...   584546633
802    4022110  Leite integral, em pó, com um teor, em peso, d...   570419562
482    3074310                                  Lulas, congeladas   547118807
263   27101249            Outras naftas, exceto para petroquímica   513288251
61    15079090                               Outros óleos de soja   507896952
1835  87032210  Automóveis com motor explosão, de cilindrada s...   478035618
3     10039080                            Outras cevadas, em grão   471425413
481    3061790      Outros camarões, que não inteiros, congelados   454598663
480    3061710               Outros camarões inteiros, congelados   393267591
146    2022090  Outras peças não desossadas de bovino, congeladas   374306639
13    10079000               Sorgo de grão, exceto para semeadura   323141277
650   38260000  Biodiesel e suas misturas, que não contenham o...   322214052
119   20041000  Batatas, preparadas ou conservadas, exceto em ...   309587199
2     10039010                                  Cevada cervejeira   291416744
1337   8083000                                     Pêras, frescas   279668933
59    15079011  Óleo de soja, refinado, em recipientes com cap...   267736149
1412  84082090  Outros motores diesel/semidiesel, para veículo...   259009901
271   27111290                        Outros propanos liquefeitos   247146170
272   27111300                                Butanos liquefeitos   223185909
218   23025000  Sêmeas, farelos e outros resíduos, de leguminosas   221608314
472    3047400           Filés de merluzas e abroteas, congelados   221123121
224   23063010  Tortas, farinhas e pellets, de sementes de gir...   220677099
276   27131100                    Coque de petróleo não calcinado   209422304
808    4061010         Queijo tipo mussarela, fresco (não curado)   208027479
817    4090000                                        Mel natural   207654298

In [94]:
ArgentinaExportNCM.groupby('Pais')['FOB(USD)'].sum().reset_index().sort_values('FOB(USD)', ascending=False).head(15)

                           Pais     FOB(USD)
21                       Brasil  12783028593
31                        China   9716808706
57               Estados Unidos   8179571293
30                        Chile   6281187597
79                        India   5471702593
177                    Viet Nam   2731224033
129                        Perú   2549209076
128                Países Bajos   2076230914
158                       Suiza   2062879942
174                     Uruguay   1782774319
4                Arabia Saudita   1576384966
127                    Paraguay   1369459858
29                       Canadá   1300758766
78   Indeterminado (continente)   1285025962
80                    Indonesia   1240657031

In [95]:
ArgentinaEXP_IMP.head(400)

,CO_NCM,NO_NCM_POR,Exportaciones
8139,99999999,Sin descripción,9865564049
894,27090010,Óleos brutos de petróleo,5959051521
354,10059010,"Milho em grão, exceto para semeadura",5947257801
765,23040010,"Farinhas e pellets, da extração do óleo de soja",5286323943
481,15071000,"Óleo de soja, em bruto, mesmo degomado",5118628924
...,...,...,...
6947,85176299,Outros aparelhos receptores radiotelefonia/rad...,3939982
3308,39259090,Outros artefatos para apetrechamento de constr...,3916977
715,21069010,Outras preparações para elaboração de bebidas,3844186
774,23099010,Preparações destinadas a fornecer ao animal a ...,3842358
5913,84213990,Outros aparelhos para filtrar ou depurar gases,3837124

In [96]:
ArgentinaImportNCM

,CO_NCM,NO_NCM_POR,Pais,CIF(USD)
0,1012100,Cavalos reprodutores de raça pura,Argentina,7541
1,1012100,Cavalos reprodutores de raça pura,Brasil,30557
2,1012100,Cavalos reprodutores de raça pura,Chile,18184
3,1012100,Cavalos reprodutores de raça pura,Estados Unidos,384426
4,1012100,Cavalos reprodutores de raça pura,Uruguay,7914
...,...,...,...,...
385925,99980500,NaN,Eslovaquia,12
385926,99980500,NaN,Eslovenia,6
385927,99980500,NaN,República Checa,4
385928,99980500,NaN,Serbia,7
385929,99980500,NaN,Australia,0

In [97]:
ArgentinaImportNCM.rename(columns={'NCM':'CO_NCM'}, inplace=True)

In [98]:
df_ncm['CO_NCM'] = df_ncm['CO_NCM'].astype('int')

In [99]:
ArgentinaImportNCM = ArgentinaImportNCM.merge(df_ncm[['CO_NCM']], on = 'CO_NCM', how='left')

In [100]:
ArgentinaImportNCM

,CO_NCM,NO_NCM_POR,Pais,CIF(USD)
0,1012100,Cavalos reprodutores de raça pura,Argentina,7541
1,1012100,Cavalos reprodutores de raça pura,Brasil,30557
2,1012100,Cavalos reprodutores de raça pura,Chile,18184
3,1012100,Cavalos reprodutores de raça pura,Estados Unidos,384426
4,1012100,Cavalos reprodutores de raça pura,Uruguay,7914
...,...,...,...,...
385925,99980500,NaN,Eslovaquia,12
385926,99980500,NaN,Eslovenia,6
385927,99980500,NaN,República Checa,4
385928,99980500,NaN,Serbia,7
385929,99980500,NaN,Australia,0

In [101]:
ArgentinaImportNCM = ArgentinaImportNCM[['CO_NCM', 'NO_NCM_POR', 'Pais', 'CIF(USD)']]

In [102]:
ArgentinaImportNCMAgregado = ArgentinaImportNCM.groupby(['CO_NCM', 'NO_NCM_POR','Pais'])['CIF(USD)'].sum().reset_index()

In [103]:
ArgentinaImportNCMAgregado['CIF(USD)'].sum()

np.int64(74584478161)

In [104]:
ArgentinaImportNCMAgregado.sort_values('CIF(USD)', ascending=False, inplace=True)

In [105]:
ArgentinaImportNCMAgregado.head(15)

,CO_NCM,NO_NCM_POR,Pais,CIF(USD)
1196,12019000,"Soja, mesmo triturada, exceto para semeadura",Paraguay,2063579846
66082,87032210,"Automóveis com motor explosão, de cilindrada s...",Brasil,1318765686
66071,87032100,"Automóveis com motor explosão, de cilindrada n...",Brasil,1222595645
66103,87032310,"Automóveis com motor explosão, 1500 < cm3 <= 3...",Brasil,913565572
65989,87012100,"Tratores rodoviários para semirreboques, unica...",Brasil,895326987
3902,27101921,Gasóleo (óleo diesel),Estados Unidos,587130712
66239,87043190,Outros veículos automóveis com motor a explosã...,Brasil,548569930
60359,85177900,"Outras partes de aparelhos telefônicos, inclui...",Viet Nam,443065366
60318,85177900,"Outras partes de aparelhos telefônicos, inclui...",China,442718234
4058,27111100,Gás natural liquefeito,Estados Unidos,350510806
66818,87084080,Outras caixas de marchas,Japón,339010289
52285,84713019,Outras máquinas digitais para processamento de...,China,311284901
11534,30021590,"Outros produtos imunológicos, apresentados em ...",Suiza,299639647
66144,87034000,"Outros veículos, equipados para propulsão, sim...",Brasil,286490528
66201,87042210,"Chassis com motor diesel e cabina, 5 toneladas...",Brasil,284504556

In [106]:
ArgentinaImportNCM.groupby(['CO_NCM', 'NO_NCM_POR'])['CIF(USD)'].sum().reset_index().sort_values('CIF(USD)', ascending=False).head(15)

        CO_NCM                                         NO_NCM_POR    CIF(USD)
354   12019000       Soja, mesmo triturada, exceto para semeadura  2241009749
7192  87032210  Automóveis com motor explosão, de cilindrada s...  1717730353
7194  87032310  Automóveis com motor explosão, 1500 < cm3 <= 3...  1711427997
7191  87032100  Automóveis com motor explosão, de cilindrada n...  1249018457
2262  30021590  Outros produtos imunológicos, apresentados em ...   962418673
7176  87012100  Tratores rodoviários para semirreboques, unica...   927991555
6815  85177900  Outras partes de aparelhos telefônicos, inclui...   894190206
7220  87043190  Outros veículos automóveis com motor a explosã...   844396143
833   27101921                              Gasóleo (óleo diesel)   840570049
7258  87084080                           Outras caixas de marchas   767614217
2462  31054000  Diidrogeno-ortofosfato de amônio (fosfato mono...   695993237
2439  31021010  Ureia, mesmo em solução aquosa, com teor de ni...   695655345
7252  87082999  Outras partes e acessórios de carrocerias para...   692113336
845   27111100                             Gás natural liquefeito   608085374
7284  87089990  Outras partes e acessórios para tratores e veí...   605435032

In [107]:
ArgentinaImportNCM.groupby('Pais')['CIF(USD)'].sum().reset_index().sort_values('CIF(USD)', ascending=False).head(15)

                              Pais     CIF(USD)
22                          Brasil  18356830382
34                           China  17940803137
58                  Estados Unidos   6610056529
152  República Federal de Alemania   3135667032
142                       Paraguay   2957977871
174                      Tailandia   2116801890
127                         México   1722769244
93                          Italia   1564027749
85                           India   1436182872
95                           Japón   1424775451
195                       Viet Nam   1322169872
84      Indeterminado (continente)   1206024914
57                          España   1167242181
66                         Francia   1123944866
33                           Chile    870211327

In [108]:
ArgentinaExportNCM.to_csv('ExportArgentinaINDEC.csv')

In [109]:
ArgentinaEXP_IMP.to_csv('ExportArgentinaMERCORSUR.csv')

In [110]:
ArgentinaEXP_IMP['Exportaciones'].sum()

np.int64(87076964335)